- FileZilla/FileZillaURLProvider.py
This should be a workaround for the version problem that has cropped up with FileZilla. Mentioned here: autopkg/keeleysam-recipes#16
> Fix for version not being set

- Github/Github.download.recipe
- Github/Github.munki.recipe
- Quicksilver/Quicksilver.download.recipe
Added CodeSignatureVerifier steps to a couple of recipes we're using.
> Added CodeSignatureVerifier to GitHub and Quicksilver recipes

- ParallelsDesktop/ParallelsDesktop10.munki.recipe
> cleaned up hard links, pkginfo now uses installs

- Github/Github.download.recipe
while we’re here, bump min version
> name change for Github

- ParallelsDesktop/ParallelsDesktop10.munki.recipe
- ParallelsDesktop/ParallelsURLProvider.py
But admin password is still required on the first run of an installed/updated PD10 package.
> Fixes to make PD10.munki build and install

- SublimeText/SublimeText3.download.recipe
- SublimeText/SublimeText3.install.recipe
Bumped min vars accordingly, tested through to install
> Add CodeSIgnVerif, install recipes

- iTerm2/iTerm2.download.recipe
I think you should verify the code signing after every download
> CodeSignatureVerifier already at download

- StuffIt/StuffItExpander.download.recipe
Added in code signature verification for StuffIt Expander's download recipe.
> Code sig ver for StuffIt Expander

- Flux/Flux.download.recipe
- Flux/Flux.munki.recipe
• Moved Unarchiver step to .download for CodeSignatureVerifier
• Added CodeSignatureVerifier to .download
• Removed Unarchiver from .munki
> Added CodeSignatureVerifier

- Opera/Opera.install.recipe
I made an install recipe for Opera, if you'd like to add it go ahead.
Cheers
Graham
> Install recipe for Opera

- FileZilla/FileZillaURLProvider.py
> Changed "update_url" to HTTPS

- FileZilla/FileZillaURLProvider.py
This will bypass certificate verification in SSL (HTTPS)
> Bypass SSL: CERTIFICATE_VERIFY_FAILED

- FileZilla/FileZillaURLProvider.py
product_name rely on the NAME variable that will certainly be set to a lowercase one since also used by munki as file name
> Turning FileZillaURLProvider into case insentive mode for product_name value

- iTerm2/iTerm2.download.recipe
CodeSignatureVerifier requirement changed
Also changed the input_path of the CodeSignatureVerifier with a wildmark on .app file.
> CodeSignatureVerifier requirement changed

- FileZilla/FileZilla.download.recipe
- FileZilla/FileZilla.munki.recipe
> Replace FileZillaURLProvider with URLTextSearcher

- Flux/Flux.download.recipe
> Update Sparkle Feed URL for Flux

- FileZilla/FileZilla.download.recipe
Otherwise CodeSigVerifier gets upset cause of cached stuff
> We should purge_destination

- Duo/Duo Device Health.munki.recipe
> Update Duo Device Health.munki.recipe

- Duo/Duo Device Health.download.recipe
Addresses #151, they're using a json feed internally as of 3.x, may as well just grab the dl link from the shasums page and not do custom stuff since they're bizarre
> Fix DDH fetching

- Opera/Opera.download.recipe
Based on what was returned in PPPC Utility using Opera version 95.0.4635.37
> [Opera] Update code signature

- Duo/Duo Device Health.pkg.recipe
This PR updates pkg recipe to work with new updates in download recipe introduced in #153.
> Fix Duo Device Health pkg recipe

- Opera/OperaURLProvider.py
fix opera download processor for 100.x.x.x verisons
> fix opera download processor for 100.x.x.x verisons

- Caffeine/Caffeine.download.recipe
- Caffeine/Caffeine.munki.recipe
- Duo/Duo Desktop.munki.recipe
Hi, @keeleysam 
The developers of Caffeine are no longer releasing via the GitHub repo. 
This PR rewrites the recipes to account for the new download location, and the different download version available. Given it's a substantial change we're happy to host the rewrite in our repo? 
```
For the OS_VERSION_DOWNLOAD variable please use:
- "sonoma"
- "ventura"
- "monterey"
``` 
Output from a successful Sonoma run
```
autopkg run -v Caffeine.munki.recipe
Looking for com.github.keeleysam.recipes.Caffeine.download...
Did not find com.github.keeleysam.recipes.Caffeine.download in recipe map
Rebuilding recipe map with current working directories...
Looking for com.github.keeleysam.recipes.Caffeine.download...
Found com.github.keeleysam.recipes.Caffeine.download in recipe map
**load_recipe time: …
```
> Caffeine Recipe Rewrite
