autopkg/keeleysam-recipes

CarbonCopyCloner/CarbonCopyCloner.download.recipe, CarbonCopyCloner/CarbonCopyCloner.install.recipe, CarbonCopyCloner/CarbonCopyCloner.munki.recipe, CarbonCopyCloner/CarbonCopyCloner.pkg.recipe
As 3.4.x seems to be EOL at this point, switching to ccc-4.xml URL with 'native' user agent. Still getting intermittent timeouts when actually downloading, but functional now. Added CertSigVerification, added
install recipe, broke with previous identifier naming convention for pkg since it changes folder to look like a pkg in the Finder otherwise. Bumped recipe min vers accordingly to accommodate CodeSigVerif and installer
Lightly tested, buyer beware! 😜
=> Ccc4 url+pkg&install recipes

Github/Github.munki.recipe
This seems to prevent the privileged helper tool prompt for admin credentials when GitHub is first launched.
=> Add postinstall_script to symlink the 'github' CLI tool

Opera/Opera.download.recipe, Opera/Opera.munki.recipe, Opera/OperaURLProvider.py
I've created a new Opera Recipe \ Processor.  It retrieves the download URL from the public ftp located here: http://get.geo.opera.com/ftp/pub/opera/desktop/ As opposed to the download link on the homepage.  This gives the advantage that the download URL is less likely to go out of date.  The current processor downloads Opera 15 when version 24 is current
=> New Opera Recipe

CarbonCopyCloner/CarbonCopyCloner.munki.recipe
Didn’t update to take into account CCC is now a zip download, which requires unarchive-dmgCreate-munkiimport dance. Checks out when tested, please verify.
=> CCC munki fix - to reflect change to zip

Flux/Flux.download.recipe, GoogleTalkPlugin/GoogleTalkPlugin.download.recipe, GoogleTalkPlugin/GoogleTalkPlugin.munki.recipe, Handbrake/Handbrake.download.recipe, Handbrake/Handbrake.munki.recipe, Panic/Coda.download.recipe, Panic/Coda.munki.recipe, Panic/Coda2.download.recipe, Panic/Coda2.munki.recipe, Panic/Transmit.download.recipe, Panic/Transmit.munki.recipe, Panic/Unison.download.recipe, Panic/Unison.munki.recipe, PrimateLabs/Geekbench2.download.recipe, PrimateLabs/Geekbench2.munki.recipe, PrimateLabs/Wiinote.download.recipe, PrimateLabs/Wiinote.munki.recipe, gfxCardStatus/gfxCardStatus.download.recipe, iTerm2/iTerm2.download.recipe, iTerm2/iTerm2.munki.recipe
For new identifiers, used Sam's standard `com.github.keeleysam.autopkg.download.NAME` format.
Fixes #49.
=> Split munki recipes into download + munki recipes.

SurteesStudios/Bartender.download.recipe
The sparkle feed for Bartender is now served over HTTPS, and plain requests receive HTTP 302. AutoPkg doesn't deal with this gracefully so instead the recipe fails. A tiny change to SPARKLE_FEED_URL should sort that out!
=> Use HTTPS to fetch Bartender

FileZilla/FileZilla.download.recipe
Due to the use of sourceforge mirrors, the ETag and Modified Dates cannot be used.
Added Filename to have Unarchiver choosing the last downloaded file.
=> CHECK_FILESIZE_ONLY and Filename

CordlessDog/Stay.munki.recipe
Stay is now distributed as a dmg that encases the application.
Removing unneeded Unarchiver and DmgCreator processors and adjusted
MunkiImporter pkg_path.
=> Fixing Stay.munki

CarbonCopyCloner/CarbonCopyCloner.download.recipe, CarbonCopyCloner/CarbonCopyClonerURLProvider.py
Updating CCC download recipe to utilize provider. Fixes issue #73.
=> Adding CarbonCopyClonerURLProvider.py to get latest zip URL 

FileZilla/FileZilla.download.recipe
even if there's malware elsewhere in how it's distributed, knowing that
the app bundle is signed is a good-to-have
=> add codesigverification to filezilla

FileZilla/FileZilla.download.recipe
CodeSignatureVerifier processor can do a .dmg but not a .tar.gz. Needs to be unarchived first.
=> Fixed code signature verification

FileZilla/FileZilla.download.recipe
Added Unarchiver processor because of tar.bz2 file and changed the CodeSignatureVerifier input_path to meet the download location of the unarchived file.
=> Added Unarchiver processor changed CodeSignatureVerifier input_path

FileZilla/FileZilla.download.recipe
Add Unarchiver Processor to fix glob error for recent CodeSignatureVerifier commit. (https://github.com/autopkg/keeleysam-recipes/commit/f8fe7b03b274cfff75c17f274b0824ef5556b05b)
```
CodeSignatureVerifier
{'Input': {'input_path': u'/Users/ladmin/Library/AutoPkg/Cache/com.github.keeleysam.recipes.FileZilla.download/downloads/FileZilla.app',
'requirement': u'identifier "org.filezilla-project.filezilla" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = "5VPGKXL75N"'}}
Error processing path '/Users/ladmin/Library/AutoPkg/Cache/com.github.keeleysam.recipes.FileZilla.download/downloads/FileZilla.app' with glob. 
Failed.
```
The munki recipe should probably …
=> Add Unarchiver Processor to fix glob error

FileZilla/FileZilla.download.recipe
The Filezilla download server provided by the Filezilla update service requires `FileZilla` as a `user-agent`. Without the required `user-agent` the download server redirects the download to https://filezilla-project.org/
=> Add user-agent for Filezilla download - Fix #93

Opera/Opera.download.recipe, Opera/OperaURLProvider.py
Their download URL changed and there's only one `desktop` folder now. Code signature changed too.
```
$ autopkg run ./Opera.munki.recipe -v                                                  
Processing ./Opera.munki.recipe...
WARNING: ./Opera.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
OperaURLProvider
OperaURLProvider: Found URL http://get.geo.opera.com/ftp/pub/opera/desktop/56.0.3051.31/mac/Opera_56.0.3051.31_Setup.dmg
URLDownloader
URLDownloader: Storing new Last-Modified header: Tue, 25 Sep 2018 12:05:09 GMT
URLDownloader: Downloaded /Users/cwhits/Library/AutoPkg/Cache/com.github.keeleysam.recipes.Opera.munki/downloads/Opera.dmg
CodeSignatureVerifier
CodeSignatureVerifier: Mounted disk image …
```
=> [Opera] Update download url and code signature

CarbonCopyCloner/CarbonCopyCloner.download.recipe
Removing the `request_headers` key from the `URLDownloader` processor as the `%USER_AGENT%` variable is not being set or used any more.
Currently running the recipe generates the following warning:
>Use of undefined key in variable substitution: u'USER_AGENT'
=> Resolved warning for unused variable `USER_AGENT`

Opera/OperaURLProvider.py
Finds only updates where "mac/" is available (code from #66) and ignores files which do not end with .dmg like "_Setup.dmg.sha256sum".
=> Detecting only mac/ folders while ignoring .sha256sum files

Duo/Duo Device Health.download.recipe, Duo/Duo Device Health.munki.recipe
its a pkg in a dmg - codesigning was looking for an app bundle.  added a crude extractor to the munki flow to pass the pkg to the importer.
todo:
probably should add an extractor to get the app bundle out so you can read its info.plist to be sure its the correct version, and get an installs array out then merge it.
=> fix initial issues with duo recipe

CarbonCopyCloner/CarbonCopyClonerURLProvider.py, FileZilla/FileZillaURLProvider.py, GoogleTalkPlugin/MunkiPkginfoReceiptsEditor.py, Opera/OperaURLProvider.py, ParallelsDesktop/ParallelsURLProvider.py
In order to make your processors more compatible with AutoPkg running in Python 3, I've applied a few adjustments suggested by `python-modernize`, `pylint --py3k`, and `pylint` in general.
More adjustments may need to be made manually later (including moving away from the `cmp()` builtin and finding a replacement for `urllib2.HTTPRedirectHandler`), but this should catch the low-hanging fruit right now.
=> Basic python3 compatibility

Flux/Flux.download.recipe
It looks like the Sparkle feed has changed, and the old one is producing errors. This one works.
=> Update Flux.download recipe

ParallelsDesktop/ParallelsURLProvider.py
This change reworks the Opera URL provider to use the new [URLGetter superclass](https://github.com/autopkg/autopkg/wiki/Downloading-from-the-Internet-in-Custom-Processors), eliminating the need for urllib2 and easing the transition to Python 3 / AutoPkg 2.
Here's the run log for the download recipe after the change: https://gist.github.com/homebysix/8b936c8a9dd6b0e7db6b0b1b179b02f8
=> Update Parallels URL provider to use URLGetter

Opera/OperaURLProvider.py
This change reworks the Opera URL provider to use the new [URLGetter superclass](https://github.com/autopkg/autopkg/wiki/Downloading-from-the-Internet-in-Custom-Processors), eliminating the need for urllib2 and easing the transition to Python 3 / AutoPkg 2.
Additionally, I added the Opera version to the output variables. Even though it's not needed for your recipes, it may be useful to others and it was cheap to obtain.
I've also reworked the loop that parses the directory listing to better handle list of versions that aren't already sorted alphabetically, by using `links.remove(max(links))` instead of `links.pop()`. I don't imagine that the directory listing sort direction will change, but just in case this should cover you.
Here's the run log for the download recipe after the change: …
=> Use URLGetter, add version output variable, and switch to HTTPS for Opera URL provider

GoogleTalkPlugin/MunkiPkginfoReceiptsEditor.py
Replace FoundationPlist, which has been retired in AutoPkg 2, with plistlib
=> FoundationPlist -> plistlib

Duo/Duo Device Health.download.recipe
At some point duo started using a new feed url.
~~~shell
defaults read /Applications/Duo\ Device\ Health.app/Contents/Info.plist SUFeedURL
https://dl.duosecurity.com/DuoDeviceHealth-appcast-v2-macos-latest.xml
~~~
=> Update sparkle feed url for duo device health recipe

Bjango/iStatMenus.download.recipe, Bjango/iStatMenus.munki.recipe
- Move Unarchiver from munki recipe to download recipe
- Add missing CodeSignatureVerifier
- Set default NAME input variable to iStatMenus
Verbose recipe run;
```
autopkg run ~/Documents/git/keeleysam-recipes/Bjango/iStatMenus.download.recipe -vv
Processing /Users/admin/Documents/git/keeleysam-recipes/Bjango/iStatMenus.download.recipe...
WARNING: /Users/admin/Documents/git/keeleysam-recipes/Bjango/iStatMenus.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLDownloader
{'Input': {'filename': 'iStatMenus.zip',
'request_headers': {'user-agent': 'Mozilla/5.0 (Macintosh; Intel '
'Mac OS X 10_8_3) '
'AppleWebKit/536.28.10 (KHTML, '
'like Gecko) Version/6.0.3 '
'Safari/536.28.10'},
'url': 'https://download.bjango.com/istatmenus/'}} …
```
=> Update iStat Menu recipes

Duo/Duo Device Health.pkg.recipe
This pull request removes unused instances of `BUNDLE_ID` from recipe input variables, which will help reduce confusion by new AutoPkg users and simplify overrides created from this point on.
Making `BUNDLE_ID` available as an input variable is a common practice in AutoPkg recipes that use the [PkgCreator](https://github.com/autopkg/autopkg/wiki/Processor-PkgCreator) processor ([example](https://github.com/autopkg/homebysix-recipes/blob/4fec9244a3af0f9b7c8f61f35a5cd7f4622fb162/soma-zone/LaunchControl.pkg.recipe#L40-L41)). It's likely that these recipes transitioned from PkgCreator to the more streamlined [AppPkgCreator](https://github.com/autopkg/autopkg/wiki/Processor-AppPkgCreator) processor some time ago, but the now-unused input variable for `BUNDLE_ID` was never removed.
Recipe run …
=> Remove unused BUNDLE_ID input var

iTerm2/iTerm2.download.recipe
Looks like the Sparkle feed has changed.
=> iTerm2 - Sparkle Feed

Opera/OperaURLProvider.py
Update OperaURLProvider's calls to retrieve web pages by UTF-8 encoding them, otherwise the byte to string conversion implied by the regex and the "+" operator won't work.
=> OperaURLProvider.py now works with page encodings

Duo/Duo Device Health.pkg.recipe
It appears Duo is now delivering a package wrapped in a disk image; this PR updates the recipe to copy (and version) that package out of the disk image.
=> Update Duo Device Health pkg recipe

Duo/Duo Device Health.download.recipe, Duo/Duo Device Health.munki.recipe
munki handles dmg's just fine... the item on the sparkle feed is even named properly with a hyphen before the version... removed superfluous actions
=> remove superfluous pkg unpacking

Duo/Duo Device Health.pkg.recipe
This fixes an error where the DMG fails to mount due to a difference in the %NAME% variable vs. what the DMG is actually called.
Context: https://macadmins.slack.com/archives/C056155B4/p1623336389039500
=> Update Duo Device Health.pkg.recipe

Opera/Opera.munki.recipe
Propose an update in order to make Opera's CFBundleVersion the resulting Munki pkginfo version due to numerous releases under one ##.# version number. (e.g. 91.0.4516.16, 91.0.4516.20, 91.0.4516.65)
=> Make Opera pkginfo version CFBundleVersion

osquery/osquery.download.recipe, osquery/osquery.install.recipe
- switched to `GitHubReleasesInfoProvider` to obtain download URL (also obtains version string as `%version%` which can be used for child recipes)
- updated code signature #138
=> switched to GitHubReleasesInfoProvider

osquery/osquery.download.recipe
After getting a Windows zip-file I added a regex to grab the .pkg instead
=> Add regex to download the macOS pkg

Duo/Duo Desktop.download.recipe
Duo Desktop 6.10.0.0 was released, but the recipe didn't find it because the existing regex only matches single digits.
This PR allows unlimited digits in each version component.
=> [Duo Desktop] allow multi-digit version numbers

Colloquy/Colloquy.download.recipe, StuffIt/StuffItExpander.download.recipe
It's important to use HTTPS for downloading software whenever possible in order to avoid the possibility of person-in-the-middle attacks (like the one that affected the Sparkle update framework [in January 2016](https://vulnsec.com/2016/osx-apps-vulnerabilities/)).
For this pull request, I detected and changed to HTTPS URLs automatically using my [HTTPS Spotter](https://www.elliotjordan.com/posts/autopkg-https/) script, and then tested all changed recipes manually to ensure exit codes of recipe run remains the same before/after the change.
This PR was submitted using [Repo Lasso](https://github.com/homebysix/repo-lasso).
Thanks for considering!
=> Update all available URLs from HTTP to HTTPS

FileZilla/FileZilla.download.recipe
This PR deprecates the non-working FileZilla recipes and points to alternatives that currently require playwright to be installed.
=> Add DeprecationWarning for FileZilla recipes
